demeter-run/fabric

Cargo.lock, src/domain/events.rs, src/domain/management/account.rs, src/domain/management/mod.rs, src/drivers/event/mod.rs, src/drivers/grpc/account.rs, src/drivers/grpc/mod.rs, src/drivers/monitor/mod.rs
=> Basic account creation

Cargo.lock, Cargo.toml, examples/config.toml, examples/docker-compose.yaml, src/bin/daemon.rs, src/bin/rpc.rs, src/driven/kafka/mod.rs, src/drivers/event/mod.rs, src/drivers/grpc/mod.rs, src/drivers/monitor/mod.rs
=> Change kafka library

Cargo.lock, Cargo.toml, src/domain/mod.rs, src/domain/project.rs, src/domain/resource.rs, src/driven/cache/project.rs, src/driven/cache/resource.rs, src/drivers/grpc/mod.rs, src/drivers/grpc/project.rs, src/drivers/grpc/resource.rs
=> Implement RPC to list port of a project

src/drivers/monitor/mod.rs
=> fix: Dont crash daemon on error

.gitignore, .sqlx/query-2ddf3f61026a7e5174cf63ffc37b6c02b7c4091081b9fcc2cd2304d316f5c75e.json, .sqlx/query-6668aa0b6afbd8a254f0fd4ab159ba404adb74fa0a95d301ecb548cfdc0a39c5.json, .sqlx/query-f28b485402b94ee5a2bc02faea75e9ae2e582f57678d6138b3e958510e0330bd.json, Cargo.lock, Cargo.toml, src/domain/event/mod.rs, src/domain/project/cache.rs, src/domain/project/command.rs, src/domain/project/mod.rs, src/domain/resource/command.rs, src/driven/cache/project.rs, src/drivers/cache/mod.rs, src/drivers/grpc/project.rs
=> chore: Implement ProjectUpdate

Cargo.lock, src/drivers/grpc/project.rs
=>  Implement mock endpoints for all remaining flows

Cargo.lock, src/domain/auth/mod.rs, src/domain/event/mod.rs, src/domain/metadata/command.rs, src/domain/metadata/mod.rs, src/domain/project/cache.rs, src/domain/project/cluster.rs, src/domain/project/command.rs, src/domain/project/mod.rs, src/domain/resource/cache.rs, src/domain/resource/cluster.rs, src/domain/resource/command.rs, src/domain/usage/cache.rs, src/domain/usage/cluster.rs, src/domain/usage/command.rs, src/driven/cache/project.rs, src/drivers/grpc/project.rs
=> Implement fetch team invites

.github/workflows/deploy.yml
=> fix: fixed image tag

Cargo.lock, src/domain/project/cache.rs, src/domain/project/command.rs, src/driven/cache/project.rs, src/drivers/grpc/project.rs
=> Implemented fetch project users

.sqlx/query-09183103c0d4febfc5f971af4f30534e689a66fa3951bc69f24812de3c0ed447.json, Cargo.lock, src/domain/event/mod.rs, src/domain/project/cache.rs, src/domain/project/command.rs, src/domain/project/mod.rs, src/driven/cache/project.rs, src/drivers/cache/mod.rs, src/drivers/grpc/project.rs
=> Implemented delete user from a project

Cargo.lock, src/domain/project/cache.rs, src/domain/project/command.rs, src/driven/cache/project.rs, src/drivers/grpc/project.rs
=> Implemented resend project user invite

src/domain/project/command.rs
=> Implemented delete project validation

.sqlx/query-ab3d742e1ccdeb23fed0f17695a63c926ee390f8a93d6e203c7283cd97ba7e7a.json, Cargo.lock, src/domain/event/mod.rs, src/domain/project/cache.rs, src/domain/project/command.rs, src/driven/cache/project.rs, src/drivers/cache/mod.rs, src/drivers/grpc/project.rs
=> Implemented project secret deletion

Cargo.lock, src/domain/auth/mod.rs, src/domain/project/command.rs, src/domain/resource/command.rs, src/domain/usage/command.rs, src/drivers/grpc/project.rs
=> Implement find project by namespace

Cargo.lock, src/domain/project/command.rs, src/drivers/grpc/project.rs
=> Implemented fetch project by id

src/domain/usage/command.rs
=> Update usage domain to accept member calls

Cargo.lock, src/drivers/grpc/usage.rs
=> Mock cost field in the rpc return values

.github/iac/main.tf, .github/workflows/deploy.yml, bootstrap/daemon/main.tf
=> Configure daemon CD

.github/iac/main.tf, Cargo.lock, src/domain/auth/mod.rs, src/domain/project/command.rs, src/domain/project/mod.rs, src/driven/auth0/mod.rs, src/drivers/grpc/project.rs
=> Implement data aggregation for project users

.github/iac/main.tf, .gitignore, bootstrap/daemon/config.tf, bootstrap/daemon/daemon.toml.tftpl, bootstrap/daemon/main.tf, bootstrap/daemon/sts.tf, src/bin/daemon.rs, src/domain/event/mod.rs, src/domain/resource/cache.rs, src/domain/usage/cache.rs, src/domain/usage/cluster.rs, src/domain/usage/mod.rs, src/driven/cache/resource.rs, src/driven/cache/usage.rs, src/driven/prometheus/usage.rs, src/drivers/cache/mod.rs, src/drivers/usage/mod.rs, test/fabric.manifest.yaml
=> Improve usage driver to send usage based on cache

.gitignore, .sqlx/query-4d25cb253b95aecdaaf50b04ec558d07eaeaef22a16a7966aa423efe690cc5a4.json, Cargo.lock, src/domain/event/mod.rs, src/domain/project/cache.rs, src/domain/project/command.rs, src/driven/cache/project.rs, src/drivers/cache/mod.rs, src/drivers/grpc/project.rs
=> Implemented delete pending user invite

bootstrap/rpc/crds/blockfrostport.hbs, bootstrap/rpc/crds/cardanonodeport.hbs, bootstrap/rpc/crds/dbsyncport.hbs, bootstrap/rpc/crds/kupoport.hbs, bootstrap/rpc/crds/marloweport.hbs, bootstrap/rpc/crds/mumakport.hbs, bootstrap/rpc/crds/ogmiosport.hbs, bootstrap/rpc/crds/scrollsport.hbs, bootstrap/rpc/crds/submitapiport.hbs, bootstrap/rpc/crds/utxorpcport.hbs
Close #172 
Network and tier removed.
=> Updated handlebars

src/domain/project/command.rs
=> Adjusted invite id in event

src/driven/cache/project.rs
=> Improved invitation query to return only pending

Cargo.lock, Cargo.toml, src/driven/kafka/mod.rs, src/drivers/monitor/mod.rs
Close #178 
```json
{
"annotation":{
"source":"fabric-0.1.0"
}
"created_at":"2024-10-21T16:51:25.077627515Z"
"id":"619fc14e-0f91-4427-ad4a-e37fc8b5855c"
"kind":"CardanoNodePort"
"name":"cardanonode-6ebnmf"
"project_id":"c153ccbb-fdb3-4b26-af25-474a6e1c969f"
"project_namespace":"ethereal-calmness-vfnenj"
"spec":"{\"authToken\":\"cardanonode12xgfecs3zlwd6ue44ne\",\"network\":\"mainnet\",\"throughputTier\":\"1\",\"version\":\"stable\"}"
"status":"active"
"updated_at":"2024-10-21T16:51:25.077629785Z"
}
```
=> Add an annotation to define the source of the event

Cargo.lock, src/domain/project/command.rs, src/drivers/grpc/project.rs
=> Implemented fetch me project user

src/domain/project/command.rs, src/domain/usage/command.rs
=> Recap all command permissions

src/drivers/monitor/mod.rs
=> Fix daemon error

.github/workflows/release-cli.yml, src/bin/cli.rs, src/domain/auth/mod.rs, src/domain/project/cache.rs, src/domain/project/mod.rs, src/domain/resource/cache.rs, src/domain/usage/cache.rs, src/domain/usage/mod.rs, src/driven/auth0/mod.rs, src/driven/cache/project.rs, src/driven/cache/resource.rs, src/driven/cache/usage.rs, src/drivers/billing/mod.rs
=> Reporting endpoints to cli

src/domain/project/cache.rs, src/domain/project/command.rs, src/driven/cache/project.rs, src/drivers/grpc/middlewares/auth.rs
=> Implemented support to use namespace in rpc header using secrets

README.md, examples/README.md, examples/config/cli.toml, examples/config/daemon.toml, src/bin/cli.rs, src/domain/auth/mod.rs, src/domain/project/cache.rs, src/domain/project/command.rs, src/domain/resource/cache.rs, src/domain/usage/cache.rs, src/driven/auth0/mod.rs, src/driven/cache/project.rs, src/driven/cache/resource.rs, src/driven/cache/usage.rs, src/driven/slack/mod.rs, src/drivers/backoffice/mod.rs, src/drivers/mod.rs
=> Improve backoffice cli

src/driven/prometheus/usage.rs
=> fix: adjusted prometheus query

bootstrap/rpc/crds/ogmiosport.hbs
=> Updated ogmios handlesbar

bootstrap/rpc/crds/cardanonodeport.json, src/bin/daemon.rs, src/bin/rpc.rs, src/driven/metadata/mod.rs, src/drivers/grpc/middlewares/auth.rs
=> chore: updated metadata cardano node version

src/driven/auth0/mod.rs
=> feat: improved auth error handle

src/driven/cache/migrations/20250318_index.sql
=> feat: added cache index

src/bin/cli.rs, src/bin/daemon.rs, src/bin/rpc.rs, src/drivers/backoffice/mod.rs, src/drivers/cache/mod.rs, test/dependences.manifest.yaml, test/fabric.manifest.yaml
=> feat: implemented support to usage queue

bootstrap/daemon/sts.tf, src/bin/daemon.rs, src/domain/usage/cluster.rs, src/drivers/usage/mod.rs
=> feat: implemented error metrics for usage driver

bootstrap/rpc/crds/trpport.hbs, bootstrap/rpc/crds/trpport.json
=> feat: added support to trp port

bootstrap/rpc/crds/kupoport.json
=> chore: updated kupo paid plan dns
